#!/usr/bin/env python3
"""install_fonts.py — Installs @expo-google-fonts/<family> packages and emits
the useFonts() hook snippet that needs to land in app/_layout.tsx.

This script runs npm install in --dry-run by default (so it just prints the
command). Pass --execute to actually run it. The hook snippet is always
printed to stdout regardless of execute mode.
"""

from __future__ import annotations
import argparse, json, subprocess, sys
from pathlib import Path


# Weight slug map for @expo-google-fonts packages.
# Most Google Fonts ship with these weights pre-named.
WEIGHT_SLUGS = {
    "300": "Light",
    "400": "Regular",
    "500": "Medium",
    "600": "SemiBold",
    "700": "Bold",
    "800": "ExtraBold",
}


def font_family_to_package(family: str) -> str:
    return f"@expo-google-fonts/{family.lower().replace(' ', '-')}"


def font_family_to_import(family: str) -> str:
    """'JetBrains Mono' → 'JetBrainsMono_400Regular' style imports."""
    return family.replace(" ", "")


def build_use_fonts_snippet(fonts: dict[str, str], weights: list[str]) -> str:
    """Generates the import + useFonts() lines for _layout.tsx."""
    # Each font role (display/body/mono) gets imports for each weight
    imports = []
    use_fonts_keys = []

    for role, family in fonts.items():
        package = font_family_to_package(family)
        family_import = font_family_to_import(family)
        weight_imports = [f"{family_import}_{w}{WEIGHT_SLUGS.get(w, 'Regular')}" for w in weights]
        imports.append(f"import {{ useFonts, {', '.join(weight_imports)} }} from \"{package}\";")
        for w, key in zip(weights, weight_imports):
            quoted_family = f'"{family}_{w}{WEIGHT_SLUGS.get(w, "Regular")}"'
            use_fonts_keys.append(f"  {quoted_family}: {key},")

    # We only need ONE useFonts() call — collapse them. Re-build cleaner:
    all_imports = []
    all_use_fonts_keys = []
    for role, family in fonts.items():
        package = font_family_to_package(family)
        family_import = font_family_to_import(family)
        weight_imports = [f"{family_import}_{w}{WEIGHT_SLUGS.get(w, 'Regular')}" for w in weights]
        all_imports.append(f'import {{ {", ".join(weight_imports)} }} from "{package}";')
        for w, key in zip(weights, weight_imports):
            quoted = f'"{family}_{w}{WEIGHT_SLUGS.get(w, "Regular")}"'
            all_use_fonts_keys.append(f"    {quoted}: {key},")

    snippet = f"""// === Generated by theme-setup. Paste these imports near the top of app/_layout.tsx ===
import {{ useFonts }} from "expo-font";
{chr(10).join(all_imports)}
import {{ PaperProvider }} from "react-native-paper";

import {{ appTheme }} from "@/theme/theme";

// === Replace the root component's body with this pattern ===
//
//   const [fontsLoaded] = useFonts({{
{chr(10).join(all_use_fonts_keys)}
//   }});
//
//   if (!fontsLoaded) {{
//     return null; // or a splash screen
//   }}
//
//   return (
//     <PaperProvider theme={{appTheme}}>
//       {{/* existing <Stack> or other root content */}}
//     </PaperProvider>
//   );
"""
    return snippet


def run_npm_install(project: Path, packages: list[str], execute: bool) -> int:
    cmd = ["npm", "install", *packages]
    if not execute:
        print(f"(dry-run) Would run in {project}:", file=sys.stderr)
        print("  " + " ".join(cmd), file=sys.stderr)
        return 0
    print(f"Running in {project}: {' '.join(cmd)}", file=sys.stderr)
    try:
        result = subprocess.run(cmd, cwd=project, check=True)
        return result.returncode
    except FileNotFoundError:
        sys.exit("ERROR: npm not on PATH")
    except subprocess.CalledProcessError as e:
        print(f"npm install failed with exit {e.returncode}", file=sys.stderr)
        return e.returncode


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--project", required=True)
    p.add_argument("--fonts", required=True, help="JSON dict mapping role→family, e.g. '{\"display\":\"Manrope\",\"body\":\"Inter\"}'")
    p.add_argument("--weights", default="400,500,600,700", help="Comma-separated weights to install")
    p.add_argument("--execute", action="store_true", help="Actually run npm install (default: dry-run)")
    args = p.parse_args()

    project = Path(args.project).resolve()
    if not (project / "package.json").exists():
        sys.exit(f"ERROR: no package.json in {project}")

    fonts = json.loads(args.fonts)
    weights = [w.strip() for w in args.weights.split(",")]
    packages = sorted({font_family_to_package(f) for f in fonts.values()})

    exit_code = run_npm_install(project, packages, args.execute)

    snippet = build_use_fonts_snippet(fonts, weights)
    print(snippet)

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
