// Semantic color tokens. Generated by theme-setup. Edit by hand to fine-tune.
//
// IMPORTANT: never hardcode color literals in components. Always import from
// here. Run theme-showcase route to see every token in use.

export const lightColors = {
  primary: "#5B57F5",
  secondary: "#7C5CFF",
  accent: "#E91E63",

  background: "#E8E9F3",
  surface: "#FFFFFF",
  surfaceVariant: "#D1D3E8",

  textPrimary: "#14142B",
  textSecondary: "#4E4B66",
  textDisabled: "#A0A3BD",

  // Text on dark/primary-colored surfaces
  onPrimary: "#FFFFFF",
  onDarkMuted: "rgba(255,255,255,0.7)",

  // Overlays & scrims
  scrim: "#111111",
  overlayDark: "rgba(0,0,0,0.55)",

  // Glass surfaces
  glassSurface: "rgba(255,255,255,0.72)",
  glassSurfaceHighlight: "rgba(255,255,255,0.88)",
  glassBorder: "rgba(255,255,255,0.40)",
  glassBorderStrong: "rgba(255,255,255,0.60)",
  glassText: "#14142B",
  glassTextMuted: "#4E4B66",
  glassShadow: "rgba(20,20,43,0.12)",

  // Rich page backgrounds
  backgroundGradientStart: "#E8E9F3",
  backgroundGradientEnd: "#D1D3E8",

  outline: "#D9DBE9",
  shadow: "#14142B",

  danger: "#EF4444",
  dangerOnDark: "#FF6B6B",
  success: "#34C759",
  warning: "#FFB800",
  info: "#5B57F5",
} as const;

export const darkColors = {
  primary: "#3DDBFF",
  secondary: "#C9B8E8",
  accent: "#FF2D87",

  background: "#0A0612",
  surface: "#15101F",
  surfaceVariant: "#1E1828",

  textPrimary: "#FFFFFF",
  textSecondary: "#A0A0B8",
  textDisabled: "#5A5A75",

  // Glass surfaces (dark)
  glassSurface: "rgba(30,24,40,0.72)",
  glassSurfaceHighlight: "rgba(45,38,60,0.88)",
  glassBorder: "rgba(255,255,255,0.12)",
  glassBorderStrong: "rgba(255,255,255,0.22)",
  glassText: "#FFFFFF",
  glassTextMuted: "#A0A0B8",
  glassShadow: "rgba(0,0,0,0.40)",

  // Rich page backgrounds (dark)
  backgroundGradientStart: "#0A0612",
  backgroundGradientEnd: "#1E1828",

  outline: "#2A2540",
  shadow: "#000000",

  danger: "#FF5A5A",
  success: "#3DD68C",
  warning: "#FFB547",
  info: "#3DDBFF",
} as const;

export type ColorToken = keyof typeof lightColors;
