// Semantic color tokens. Generated by theme-setup. Edit by hand to fine-tune.
//
// IMPORTANT: never hardcode color literals in components. Always import from
// here. Run theme-showcase route to see every token in use.

export const lightColors = {
  primary: "#5B57F5",
  secondary: "#7C5CFF",
  accent: "#E91E63",

  background: "#E8E9F3",
  surface: "#FFFFFF",
  surfaceVariant: "#D1D3E8",

  textPrimary: "#14142B",
  textSecondary: "#4E4B66",
  textDisabled: "#A0A3BD",

  outline: "#D9DBE9",

  danger: "#EF4444",
  success: "#34C759",
  warning: "#FFB800",
  info: "#5B57F5",
} as const;

export const darkColors = {
  primary: "#3DDBFF",
  secondary: "#C9B8E8",
  accent: "#FF2D87",

  background: "#0A0612",
  surface: "#15101F",
  surfaceVariant: "#1E1828",

  textPrimary: "#FFFFFF",
  textSecondary: "#A0A0B8",
  textDisabled: "#5A5A75",

  outline: "#2A2540",

  danger: "#FF5A5A",
  success: "#3DD68C",
  warning: "#FFB547",
  info: "#3DDBFF",
} as const;

export type ColorToken = keyof typeof lightColors;
