// Barrel for the theme module. Generated by theme-setup.
//
// Re-exports the design tokens AND aliases `appTheme` → `theme` so existing
// consumers (e.g. AppProviders) that import { theme } from "@/theme" keep
// working.

import { useTheme } from "react-native-paper";

import { lightColors, darkColors } from "./colors";

export { lightColors, darkColors } from "./colors";
export type { ColorToken } from "./colors";

export {
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  letterSpacing,
} from "./typography";
export type { FontFamilyToken, FontSizeToken, FontWeightToken } from "./typography";

export { spacing } from "./spacing";
export type { SpacingToken } from "./spacing";

export { radii } from "./radii";
export type { RadiusToken } from "./radii";

export { shadows } from "./shadows";
export type { ShadowToken } from "./shadows";

export { lightTheme, darkTheme, appTheme } from "./theme";
export { appTheme as theme } from "./theme";

// Active palette helper — pulls light/dark based on theme.dark flag.
export const usePalette = () => {
  const themeCtx = useTheme();
  return themeCtx.dark ? darkColors : lightColors;
};
