// Elevation / shadow tokens. Generated by theme-setup.
//
// RN shadows: iOS uses shadowColor/Offset/Opacity/Radius; Android uses
// elevation. We provide BOTH on every token so the same import works
// cross-platform.

import { Platform } from "react-native";
import type { ViewStyle } from "react-native";

import { lightColors } from "./colors";

type Shadow = Pick<ViewStyle, "shadowColor" | "shadowOffset" | "shadowOpacity" | "shadowRadius" | "elevation">;

const make = (offsetY: number, blur: number, opacity: number, elevation: number): Shadow => ({
  shadowColor: "#FFFFFF",
  shadowOffset: { width: 0, height: offsetY },
  shadowOpacity: opacity,
  shadowRadius: blur,
  elevation: Platform.OS === "android" ? elevation : 0,
});

export const shadows = {
  none: make(0, 0, 0, 0),
  sm: make(1, 2, 0.05, 1),
  base: make(2, 4, 0.08, 2),
  md: make(4, 8, 0.12, 4),
  lg: make(8, 16, 0.16, 8),
  xl: make(16, 24, 0.20, 12),
  glow: {
    shadowColor: "#3DDBFF",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 16,
    elevation: Platform.OS === "android" ? 8 : 0,
  } satisfies Shadow,
  glass: {
    shadowColor: lightColors.glassShadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: Platform.OS === "android" ? 8 : 0,
  } satisfies Shadow,
} as const;

export type ShadowToken = keyof typeof shadows;
