// 4pt-grid spacing tokens. Generated by theme-setup (AURA TRENCH).
//
// Provides BOTH numeric keys (spacing["4"] -> 16) and semantic aliases
// (spacing.md -> 16). New code should prefer one style consistently;
// the aliases exist to keep older scaffolded components working.

export const spacing = {
  // Numeric scale (Tailwind-style)
  "0": 0,
  "px": 1,
  "0.5": 2,
  "1": 4,
  "1.5": 6,
  "2": 8,
  "2.5": 10,
  "3": 12,
  "4": 16,
  "5": 20,
  "6": 24,
  "8": 32,
  "10": 40,
  "12": 48,
  "16": 64,
  "20": 80,
  "24": 96,

  // Semantic aliases (t-shirt scale, retained for back-compat)
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export type SpacingToken = keyof typeof spacing;
