// Composed theme. Generated by theme-setup (AURA TRENCH).
//
// Maps semantic tokens to React Native Paper MD3Theme. Each Paper variant
// references the WEIGHT-SPECIFIC fontFamily (e.g. "Inter_700Bold") so the
// weight is actually applied - RN does not swap font files based on
// fontWeight, you have to point at the right family.

import { MD3DarkTheme, MD3LightTheme, configureFonts } from "react-native-paper";
import type { MD3Theme } from "react-native-paper";

import { lightColors, darkColors } from "./colors";
import { fontFamily, fontSize, lineHeight, letterSpacing } from "./typography";

const fontConfig = {
  displayLarge:   { fontFamily: fontFamily.displayBold,     fontSize: fontSize["6xl"], lineHeight: fontSize["6xl"] * lineHeight.tight, letterSpacing: letterSpacing.tight },
  displayMedium:  { fontFamily: fontFamily.displayBold,     fontSize: fontSize["5xl"], lineHeight: fontSize["5xl"] * lineHeight.tight, letterSpacing: letterSpacing.tight },
  displaySmall:   { fontFamily: fontFamily.displayBold,     fontSize: fontSize["4xl"], lineHeight: fontSize["4xl"] * lineHeight.tight, letterSpacing: letterSpacing.tight },
  headlineLarge:  { fontFamily: fontFamily.displaySemibold, fontSize: fontSize["3xl"], lineHeight: fontSize["3xl"] * lineHeight.tight, letterSpacing: letterSpacing.normal },
  headlineMedium: { fontFamily: fontFamily.displaySemibold, fontSize: fontSize["2xl"], lineHeight: fontSize["2xl"] * lineHeight.tight, letterSpacing: letterSpacing.normal },
  headlineSmall:  { fontFamily: fontFamily.displaySemibold, fontSize: fontSize.xl,     lineHeight: fontSize.xl     * lineHeight.tight, letterSpacing: letterSpacing.normal },
  titleLarge:     { fontFamily: fontFamily.bodySemibold,    fontSize: fontSize.lg,     lineHeight: fontSize.lg     * lineHeight.normal, letterSpacing: letterSpacing.normal },
  titleMedium:    { fontFamily: fontFamily.bodyMedium,      fontSize: fontSize.base,   lineHeight: fontSize.base   * lineHeight.normal, letterSpacing: letterSpacing.normal },
  titleSmall:     { fontFamily: fontFamily.bodyMedium,      fontSize: fontSize.sm,     lineHeight: fontSize.sm     * lineHeight.normal, letterSpacing: letterSpacing.normal },
  bodyLarge:      { fontFamily: fontFamily.bodyRegular,     fontSize: fontSize.lg,     lineHeight: fontSize.lg     * lineHeight.normal, letterSpacing: letterSpacing.normal },
  bodyMedium:     { fontFamily: fontFamily.bodyRegular,     fontSize: fontSize.base,   lineHeight: fontSize.base   * lineHeight.normal, letterSpacing: letterSpacing.normal },
  bodySmall:      { fontFamily: fontFamily.bodyRegular,     fontSize: fontSize.sm,     lineHeight: fontSize.sm     * lineHeight.normal, letterSpacing: letterSpacing.normal },
  labelLarge:     { fontFamily: fontFamily.bodySemibold,    fontSize: fontSize.sm,     lineHeight: fontSize.sm     * lineHeight.normal, letterSpacing: letterSpacing.wide },
  labelMedium:    { fontFamily: fontFamily.bodyMedium,      fontSize: fontSize.xs,     lineHeight: fontSize.xs     * lineHeight.normal, letterSpacing: letterSpacing.wide },
  labelSmall:     { fontFamily: fontFamily.bodyMedium,      fontSize: 11,              lineHeight: 11              * lineHeight.normal, letterSpacing: letterSpacing.wider },
};

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: lightColors.primary,
    onPrimary: lightColors.background,
    primaryContainer: lightColors.surfaceVariant,
    onPrimaryContainer: lightColors.textPrimary,
    secondary: lightColors.secondary,
    onSecondary: lightColors.background,
    tertiary: lightColors.accent,
    onTertiary: lightColors.textPrimary,
    background: lightColors.background,
    onBackground: lightColors.textPrimary,
    surface: lightColors.surface,
    onSurface: lightColors.textPrimary,
    surfaceVariant: lightColors.surfaceVariant,
    onSurfaceVariant: lightColors.textSecondary,
    outline: lightColors.outline,
    error: lightColors.danger,
    onError: lightColors.background,
  },
  fonts: configureFonts({ config: fontConfig }),
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  dark: true,
  colors: {
    ...MD3DarkTheme.colors,
    primary: darkColors.primary,
    onPrimary: darkColors.background,
    primaryContainer: darkColors.surfaceVariant,
    onPrimaryContainer: darkColors.textPrimary,
    secondary: darkColors.secondary,
    onSecondary: darkColors.background,
    tertiary: darkColors.accent,
    onTertiary: darkColors.textPrimary,
    background: darkColors.background,
    onBackground: darkColors.textPrimary,
    surface: darkColors.surface,
    onSurface: darkColors.textPrimary,
    surfaceVariant: darkColors.surfaceVariant,
    onSurfaceVariant: darkColors.textSecondary,
    outline: darkColors.outline,
    error: darkColors.danger,
    onError: darkColors.background,
  },
  fonts: configureFonts({ config: fontConfig }),
};

export const appTheme = lightTheme;
