// Typography tokens. Generated by theme-setup (AURA TRENCH).
//
// IMPORTANT - RN font loading: each weight is loaded as its OWN font family
// name (Inter_400Regular, Inter_500Medium, etc.). Setting fontWeight on a
// generic family does not pick a different weight; you have to reference the
// weight-specific family name. The keys below match what useFonts() loads
// in app/_layout.tsx.

export const fontFamily = {
  // Display - Unbounded (heavy brutalist sans)
  display: "Unbounded_700Bold",
  displayBold: "Unbounded_700Bold",
  displaySemibold: "Unbounded_600SemiBold",
  displayMedium: "Unbounded_500Medium",
  displayRegular: "Unbounded_400Regular",

  // Body - Inter (neutral workhorse)
  body: "Inter_400Regular",
  bodyRegular: "Inter_400Regular",
  bodyMedium: "Inter_500Medium",
  bodySemibold: "Inter_600SemiBold",
  bodyBold: "Inter_700Bold",

  // Mono - Space Mono (Google Fonts package only ships 400 + 700)
  mono: "SpaceMono_400Regular",
  monoBold: "SpaceMono_700Bold",
} as const;

export const fontSize = {
  xs: 12,
  sm: 14,
  base: 16,
  lg: 18,
  xl: 20,
  "2xl": 24,
  "2.5xl": 28,
  "3xl": 30,
  "4xl": 36,
  "5xl": 48,
  "6xl": 60,
} as const;

export const fontWeight = {
  regular: "400",
  medium: "500",
  semibold: "600",
  bold: "700",
} as const;

export const lineHeight = {
  tight: 1.2,
  normal: 1.5,
  relaxed: 1.75,
} as const;

export const letterSpacing = {
  tight: -0.5,
  normal: 0,
  wide: 0.5,
  wider: 1,
} as const;

export type FontFamilyToken = keyof typeof fontFamily;
export type FontSizeToken = keyof typeof fontSize;
export type FontWeightToken = keyof typeof fontWeight;
