export const QUOTE_BUILDER_COPY = {
  title: "Build quote",
  loading: "Loading order…",
  notFound: "This order no longer exists.",
  hint: "Add the work and pricing. The customer reviews this before any work begins.",
  scheduledLabel: "Appointment time (customer's request — adjust if needed)",
  addItem: "Add line item",
  itemNamePlaceholder: "Item or service",
  pricePlaceholder: "Price",
  qtyPlaceholder: "Qty",
  earnings: "Your earnings",
  platformFee: "Platform fee",
  customerTotal: "Customer pays",
  submit: "Send quote to customer",
  submitting: "Sending…",
  submitError: "We couldn't send the quote. Please try again.",
} as const;
