// Dev-only showcase for every design token. Visit /theme-showcase in the app.
//
// This file is auto-generated by theme-setup. Edit by hand only if you're
// adding new tokens you want documented.

import { ScrollView, StyleSheet, View } from "react-native";
import { Surface, Text, useTheme } from "react-native-paper";

import { lightColors, darkColors } from "@/theme/colors";
import { fontSize, fontWeight } from "@/theme/typography";
import { spacing } from "@/theme/spacing";
import { radii } from "@/theme/radii";
import { shadows } from "@/theme/shadows";

const styles = StyleSheet.create({
  container: { padding: spacing["4"] },
  section: { marginBottom: spacing["8"] },
  sectionTitle: { marginBottom: spacing["3"], fontSize: fontSize["2xl"], fontWeight: fontWeight.bold },
  swatchRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing["3"] },
  swatch: { width: 100, height: 80, borderRadius: radii.base, padding: spacing["2"], justifyContent: "flex-end" },
  swatchLabel: { fontSize: fontSize.xs, color: "#fff", fontWeight: fontWeight.semibold },
  swatchHex: { fontSize: 10, color: "#fff", opacity: 0.85 },
  typeRow: { marginBottom: spacing["3"] },
  spacingRow: { flexDirection: "row", alignItems: "center", gap: spacing["3"], marginBottom: spacing["2"] },
  spacingBar: { backgroundColor: "#888", height: 8 },
  radiusRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing["3"] },
  radiusBox: { width: 60, height: 60, backgroundColor: "#666", justifyContent: "center", alignItems: "center" },
  shadowRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing["4"], paddingVertical: spacing["3"] },
  shadowCard: { width: 90, height: 60, borderRadius: radii.base, padding: spacing["2"], justifyContent: "center", alignItems: "center" },
});

const ColorSwatch = ({ name, hex }: { name: string; hex: string }) => (
  <View style={[styles.swatch, { backgroundColor: hex }]}>
    <Text style={styles.swatchLabel}>{name}</Text>
    <Text style={styles.swatchHex}>{hex}</Text>
  </View>
);

export const ThemeShowcaseView = () => {
  const theme = useTheme();
  const palette = theme.dark ? darkColors : lightColors;

  return (
    <ScrollView style={{ backgroundColor: theme.colors.background }} contentContainerStyle={styles.container}>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Colors</Text>
        <View style={styles.swatchRow}>
          {Object.entries(palette).map(([name, hex]) => (
            <ColorSwatch key={name} name={name} hex={hex} />
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Typography</Text>
        <Text variant="displayLarge" style={styles.typeRow}>Display Large</Text>
        <Text variant="displayMedium" style={styles.typeRow}>Display Medium</Text>
        <Text variant="headlineLarge" style={styles.typeRow}>Headline Large</Text>
        <Text variant="headlineMedium" style={styles.typeRow}>Headline Medium</Text>
        <Text variant="titleLarge" style={styles.typeRow}>Title Large</Text>
        <Text variant="bodyLarge" style={styles.typeRow}>Body Large — the quick brown fox jumps over the lazy dog</Text>
        <Text variant="bodyMedium" style={styles.typeRow}>Body Medium — the quick brown fox jumps over the lazy dog</Text>
        <Text variant="labelLarge" style={styles.typeRow}>LABEL LARGE</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Spacing</Text>
        {Object.entries(spacing).map(([token, value]) => (
          <View key={token} style={styles.spacingRow}>
            <Text style={{ width: 40 }}>{token}</Text>
            <View style={[styles.spacingBar, { width: value }]} />
            <Text>{value}px</Text>
          </View>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Radii</Text>
        <View style={styles.radiusRow}>
          {Object.entries(radii).map(([token, value]) => (
            <View key={token} style={[styles.radiusBox, { borderRadius: typeof value === "number" ? value : 0 }]}>
              <Text style={{ color: "#fff", fontSize: 10 }}>{token}</Text>
            </View>
          ))}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Shadows</Text>
        <View style={styles.shadowRow}>
          {Object.entries(shadows).map(([token, style]) => (
            <Surface key={token} style={[styles.shadowCard, style, { backgroundColor: theme.colors.surface }]}>
              <Text style={{ fontSize: fontSize.xs }}>{token}</Text>
            </Surface>
          ))}
        </View>
      </View>
    </ScrollView>
  );
};
